# Generated by Django 3.0.4 on 2020-04-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('x_coord', models.BigIntegerField()),
                ('y_coord', models.BigIntegerField()),
                ('district_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('caseId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('Id_doc_num', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('confirmed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('detail', models.CharField(max_length=15)),
                ('category_name', models.CharField(max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_corner.Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_corner.Patient')),
            ],
        ),
    ]
