# Generated by Django 3.0.4 on 2020-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_corner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='detail',
            field=models.CharField(max_length=50),
        ),
    ]
