# Generated by Django 3.0.4 on 2020-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_corner', '0002_auto_20200403_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district_name',
            field=models.CharField(max_length=30),
        ),
    ]
